### ISSUE TITLE
Resolving intersecting FPS and the need for a reverse reference from the associatedSites to the primary

### ISSUE THREAD

**Issue by brownwolf1355** [GoogleChrome/first-party-sets#20]
This issue seems to apply to both the GoogleChrome/first-party-sets repo as well as the WICG/first-party-sets repo, since it seems to hit both on the implementation of the FPS check under the first and the discussion of FPS under the second.

While the FPS check that is performed during a PR to submit an FPS does check for intersections among FPS (e.g. multiple primary domains including one or more of the same associatedSites domains), there does not appear to be a mechanism to resolve these conflicting FPS. The current behavior would indicate that the first FPS submission takes precedence even if it was a false FPS declaration (e.g., a malicious actor attempting to claim ownership of domains that it does not in fact own) and the true owner would have to somehow prove (to whom, Google Chrome?) that it is in fact the true owner of the associatedSites and not the malicious actor.

This could be resolved with the requirement that the same first_party_sets.json file is present under /.well-known on the primary domain, as well as all of the associatedSites domains. The FPS check could then validate that the all of the first_party_sets.json files match and thus prevent a malicious actor from claiming them, since they would not have the ability to place a fraudulent first_party_sets.json on the associatedSites domains.

**Comment by cfredric** [comment]
If I understand correctly, the concern is that the current submission requirements do not sufficiently prevent a malicious actor from creating a set that contains domains that aren't actually under the malicious actor's control. Is that right?

If so, then I think the Submission Guidelines actually already require what you're suggesting - so it's not actually possible for a malicious actor to create such a set *unless* they gain administrative control over the domains in question. (Your suggested requirement is that each associated/service domain duplicate the same .well-known file that the primary hosts, while our guidelines only require that the associated/service domains declare how to find the primary's file, by listing the primary domain. This choice was intentional, to reduce maintenance burden on site administrators as sets evolve over time.)

The requirement for a reverse reference (to borrow your phrase) in the Submission Guidelines is here: https://github.com/GoogleChrome/first-party-sets/blob/3035f1f15aea0d34a9ff133c0959d0c0293129ed/FPS-Submission_Guidelines.md?plain=1#L141

The guidelines also contain an example of such a reference, and the schema, here: https://github.com/GoogleChrome/first-party-sets/blob/3035f1f15aea0d34a9ff133c0959d0c0293129ed/FPS-Submission_Guidelines.md?plain=1#L205-L220

The existing automated checks validate this requirement here: https://github.com/GoogleChrome/first-party-sets/blob/3035f1f15aea0d34a9ff133c0959d0c0293129ed/FpsCheck.py#L395-L409

I'm going to tentatively close this issue, but please reopen it if I've misunderstood anything.

**Comment by brownwolf1355** [comment]
Thanks for the clarification. I realize I misunderstood the wording of the sentence you reference, "Each member domain must serve a JSON file at /.well-known/first-party-set.json. The contents of the file must name the primary domain." I also missed this in FPS checking code.

It was unclear to me what was meant by "Each member domain" and I assumed that this meant just the primary domain. It could be more explicit if it were reworded as, "Each of the associatedSites and serviceSites domain must also serve a JSON file at /.well-known/first-party-set.json. The contents of the first-party-set.json file on these domains must at a minimum name the primary domain."

I will submit a PR on the Submission Guidelines for this change.
